Vagrant.configure("2") do |config|
	is_arm = RUBY_PLATFORM.include?("arm64") || RUBY_PLATFORM.include?("aarch64")
	config.vm.define "client0" do |client|
		client.vm.box = "bento/ubuntu-26.04" if is_arm
		client.vm.box = "ubuntu/focal64" if !is_arm
		client.vm.box_architecture = "arm64" if is_arm
		client.vm.hostname = "frontend"
		config.vm.boot_timeout = 600
		#client.vm.network "forwarded_port", guest: 22, host: "2232"
		client.vm.network "private_network", ip: "10.20.30.1",netmask: "255.255.255.0", virtualbox__intnet: "intnet"
		client.vm.network "public_network", bridge: "Intel(R) Ethernet Connection (17) I219-LM"
		client.vm.provider "virtualbox" do |vb|
			#vb.customize ["modifyvm", :id, "--appendconfig", "nopti nospectre_v2 nospectre_v1 irqpoll"] if !is_arm
			#vb.customize ["storagectl", :id, "--name", "SATA Controller", "--hostiocache", "on"] if !is_arm
			#vb.customize ["modifyvm", :id, "--ioapic", "on"] if !is_arm
			#vb.customize ["modifyvm", :id, "--paravirt-provider", "hyperv"] if !is_arm
			vb.gui = !is_arm
			vb.memory = "1024"
			vb.cpus = 1
			vb.name = "frontend"
			end

		client.vm.provision "file", source: "frontend/99-installer-config.yaml", destination: "/tmp/99-installer-config.yaml"

		client.vm.provision "shell", inline: <<-SHELL
			sudo apt-get -y update
			sudo apt-get -y upgrade
			sudo apt-get -y install curl net-tools traceroute

			sudo mv /tmp/99-installer-config.yaml /etc/netplan/99-installer-config.yaml
            sudo chmod 600 /etc/netplan/99-installer-config.yaml

            sudo netplan apply

			sudo sh -c 'echo "1" > /proc/sys/net/ipv4/ip_forward'

			

			sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
			sudo sysctl -p
			

			echo "iptables-persistent iptables-persistent/autosave_v4 boolean false" | debconf-set-selections
			echo "iptables-persistent iptables-persistent/autosave_v6 boolean false" | debconf-set-selections
			DEBIAN_FRONTEND=noninteractive sudo apt-get -y install iptables-persistent
    		for EXT_IF in $(ip -o route show default | awk '{print $5}' | sort -u); do
				iptables -t nat -c POSTROUTING -s 10.20.30.0/24 -o "$EXT_IF" -j MASQUERADE 2>/dev/null \
				  || iptables -t nat -A POSTROUTING -s 10.20.30.0/24 -o "$EXT_IF" -j MASQUERADE
			done


			sudo netfilter-persistent save
		SHELL
	end

	config.vm.define "client02" do |client02|
		client02.vm.box = "bento/ubuntu-26.04" if is_arm
		client02.vm.box = "ubuntu/focal64" if !is_arm
		client02.vm.box_architecture = "arm64" if is_arm
		client02.vm.hostname = "backend"
		config.vm.boot_timeout = 600
		#client02.vm.network "forwarded_port", guest: 22, host: "2233"
		client02.vm.network "private_network", ip: "10.20.30.2",netmask: "255.255.255.0", virtualbox__intnet: "intnet"
		client02.vm.provider "virtualbox" do |vb|
			vb.gui = !is_arm
			vb.memory = "1024"
			vb.cpus = 1
			vb.name = "backend"
			end

		client02.vm.provision "file", source: "backend/99-installer-config.yaml", destination: "/tmp/99-installer-config.yaml"


		client02.vm.provision "shell", inline: <<-SHELL
			sudo apt-get -y update
			sudo apt-get -y upgrade
			sudo apt-get -y install curl net-tools traceroute

			sudo mv /tmp/99-installer-config.yaml /etc/netplan/99-installer-config.yaml
            sudo chmod 600 /etc/netplan/99-installer-config.yaml

            sudo netplan apply
		SHELL
	end

	config.vm.define "client03" do |client03|
		client03.vm.box = "bento/ubuntu-26.04" if is_arm
		client03.vm.box = "ubuntu/focal64" if !is_arm
		client03.vm.box_architecture = "arm64" if is_arm
		client03.vm.hostname = "database"
		config.vm.boot_timeout = 600
		#client03.vm.network "forwarded_port", guest: 22, host: "2233"
		client03.vm.network "private_network", ip: "10.20.30.3",netmask: "255.255.255.0", virtualbox__intnet: "intnet"
		client03.vm.provider "virtualbox" do |vb|
			vb.gui = !is_arm
			vb.memory = "1024"
			vb.cpus = 1
			vb.name = "database"
			end

		client03.vm.provision "file", source: "database/99-installer-config.yaml", destination: "/tmp/99-installer-config.yaml"


		client03.vm.provision "shell", inline: <<-SHELL
			sudo apt-get -y update
			sudo apt-get -y upgrade
			sudo apt-get -y install curl net-tools traceroute

			sudo mv /tmp/99-installer-config.yaml /etc/netplan/99-installer-config.yaml
            sudo chmod 600 /etc/netplan/99-installer-config.yaml

            sudo netplan apply
		SHELL
	end
end
